version: "3.9"
services:
  mongo:
    image: mongo:7
    container_name: agital-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  backend:
    image: agital-backend:latest
    build:
      context: ./backend
    container_name: agital-backend
    environment:
      - PORT=4000
      - MONGODB_URI=mongodb://mongo:27017/agital-shop
      - CORS_ORIGIN=http://localhost:3000,https://agital-shop.vercel.app
    depends_on:
      - mongo
    ports:
      - "4000:4000"
    restart: unless-stopped

  frontend:
    image: agital-frontend:latest
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_BASE_URL: http://backend:4000
    container_name: agital-frontend
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://backend:4000
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  mongo-data: